"""
Each new term in the Fibonacci sequence
is generated by adding the previous two
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Find the sum of all the even-valued terms in the sequence
which do not exceed four million.
"""

my_list = [1, 2]

sum_of_even = 0

while my_list[-1] < 4_000_000:
    if my_list[-1] % 2 == 0:
        sum_of_even += my_list[-1]
    my_list.append(my_list[-1] + my_list[-2])

print(sum_of_even)